---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  tasks:
  - include_role:
      name: vmware-provision

- name: Standardize the Linux VMs
  hosts: newlinuxvm
  tasks:
  - include_role:
      name: prep-new-vm 
    vars:
  - include_role:
      name: adriagalin.motd
    vars:
      ag_motd_sysadmins_signature: Ansible Sys Admins
      ag_motd_sysadmins_email: admin@example.com
  
- name: Standardize the Windows VMs
  hosts: newwindowsvm
  tasks:
  - include_role:
      name: prep-new-vm 
