---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  roles:
  - vmware-provision

- name: Standardize the new vm
  hosts: newlinuxvm:newwindowsvm
  roles:
  - prep-new-vm
