---
- name: Build a VMware guest from template
  hosts: localhost
  gather_facts: no
  roles:
  - vmware-provision

- name: Standardize the Linux VMs
  hosts: newlinuxvm
  roles:
  - prep-new-vm
  - adriagalin.motd
    vars:
      ag_motd_sysadmins_signature: Ansible Sys Admins
      ag_motd_sysadmins_email: admin@example.com
  
- name: Standardize the Windows VMs
  hosts: newwindowsvm
  roles:
  - prep-new-vm
