---
# tasks file for prep-new-vm
- name: "Running windows vm prepare"
  include_tasks: windows.yml
  when: "'newwindowsvm' in groups"

- name: "Running linux vm prepare"
  include_tasks: linux.yml
  when: "'newlinuxvm' in groups"
