
---
# defaults file for vmware-guest-provision/---

##       If these 3 are not defined, Ansible Tower will use the vcenter credential
#vc_hostname: vcenter.lab
#vc_username: username
#vc_password: password

##       If these 2 are defined as such, this will deploy a template
##       with a linked clone, based on the snapshot called ansible
##       leave these uncommented if you want to enable this feature.
#vm_linked_clone: yes
#vm_linked_snapshot: ansible


vc_datacenter: LabDC
vm_template: kev-template
vm_name: GoKEV-newvm-00000
vm_domain: lab
vm_cluster: LabCluster
vm_guestid: centos64Guest
vm_cpu_count: 1
vc_datastore: vsanDatastore
vm_disk_size: 20
vm_folder: /
vm_network: VM Network
vm_ram_mb: 1024
vm_state: poweredon
validate_certs: no
new_vm_names: []
os_type: "{{ 'windows' if 'Win' in vm_template else 'linux' }}"

